# -*- coding: utf-8 -*-
"""28_principal_component_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E-V_ZqofnHUxslchz36owxXl8m1Ic9TL

# Principal Component Analysis (PCA)

In this notebook, we use PCA to reduce dataset dimensions while preserving maximum variance.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_classification

from sklearn.preprocessing import StandardScaler

from sklearn.decomposition import PCA

X, y = make_classification(
    n_samples=200,
    n_features=5,
    n_informative=3,
    random_state=42
)

print("Original Shape:")

print(X.shape)

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

print("PCA Shape:")

print(X_pca.shape)

print(
    pca.explained_variance_ratio_
)

print(
    "Total Variance:",
    pca.explained_variance_ratio_.sum()
)

plt.figure(figsize=(8,6))

plt.scatter(
    X_pca[:,0],
    X_pca[:,1],
    c=y,
    s=70
)

plt.xlabel("Principal Component 1")

plt.ylabel("Principal Component 2")

plt.title("PCA Projection")

plt.show()

comparison = pd.DataFrame({
    "Dataset":[
        "Original",
        "After PCA"
    ],
    "Features":[
        X.shape[1],
        X_pca.shape[1]
    ]
})

comparison