# -*- coding: utf-8 -*-
"""30_pca_component_selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13JOnIg4cO0LJDJLiVE5okMUf0PKv9oJZ

# PCA Component Selection

In this notebook, we analyze how many principal components should be retained by studying explained variance and cumulative variance.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

X, y = make_classification(
    n_samples=500,
    n_features=10,
    n_informative=6,
    random_state=42
)

print(X.shape)

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

pca = PCA()

pca.fit(X_scaled)

print(
    pca.explained_variance_ratio_
)

cumulative_variance = np.cumsum(
    pca.explained_variance_ratio_
)

print(cumulative_variance)

plt.figure(figsize=(8,5))

plt.plot(
    range(
        1,
        len(pca.explained_variance_ratio_) + 1
    ),
    pca.explained_variance_ratio_,
    marker='o'
)

plt.xlabel("Principal Component")

plt.ylabel("Explained Variance")

plt.title("Scree Plot")

plt.show()

plt.figure(figsize=(8,5))

plt.plot(
    range(
        1,
        len(cumulative_variance) + 1
    ),
    cumulative_variance,
    marker='o'
)

plt.xlabel("Number of Components")

plt.ylabel("Cumulative Variance")

plt.title(
    "Cumulative Variance Explained"
)

plt.grid()

plt.show()

components_needed = np.argmax(
    cumulative_variance >= 0.90
) + 1

print(
    "Components needed for 90% variance:",
    components_needed
)

summary = pd.DataFrame({
    "Component":
    range(
        1,
        len(cumulative_variance)+1
    ),

    "Cumulative Variance":
    cumulative_variance
})

summary

"""## Conclusion

This notebook analyzed how much information each principal component retains.

Observations:
- Earlier components retain most information.
- Later components contribute less variance.
- PCA helps identify the minimum number of components needed while preserving important information.
- Component selection is based on cumulative variance rather than guessing.
"""